let[@inline] error_UniswapNonPositiveInput                         : Ligo.int = Ligo.int_from_literal "1"
let[@inline] error_UniswapTooLate                                  : Ligo.int = Ligo.int_from_literal "2"

let[@inline] error_BuyKitTooLowExpectedKit                         : Ligo.int = Ligo.int_from_literal "3"
let[@inline] error_BuyKitPriceFailure                              : Ligo.int = Ligo.int_from_literal "4"
let[@inline] error_BuyKitTooMuchKitBought                          : Ligo.int = Ligo.int_from_literal "5"

let[@inline] error_SellKitNonEmptyAmount                           : Ligo.int = Ligo.int_from_literal "6"
let[@inline] error_SellKitTooLowExpectedTez                        : Ligo.int = Ligo.int_from_literal "7"
let[@inline] error_SellKitPriceFailure                             : Ligo.int = Ligo.int_from_literal "8"
let[@inline] error_SellKitTooMuchTezBought                         : Ligo.int = Ligo.int_from_literal "9"

let[@inline] error_AddLiquidityNoTezGiven                          : Ligo.int = Ligo.int_from_literal "10"
let[@inline] error_AddLiquidityNoKitGiven                          : Ligo.int = Ligo.int_from_literal "11"
let[@inline] error_AddLiquidityNoLiquidityToBeAdded                : Ligo.int = Ligo.int_from_literal "12"
let[@inline] error_AddLiquidityTooLowLiquidityMinted               : Ligo.int = Ligo.int_from_literal "13"
let[@inline] error_AddLiquidityTooMuchKitRequired                  : Ligo.int = Ligo.int_from_literal "14"
let[@inline] error_AddLiquidityZeroKitDeposited                    : Ligo.int = Ligo.int_from_literal "15"

let[@inline] error_RemoveLiquidityNonEmptyAmount                   : Ligo.int = Ligo.int_from_literal "16"
let[@inline] error_RemoveLiquidityNoLiquidityBurned                : Ligo.int = Ligo.int_from_literal "17"
let[@inline] error_RemoveLiquidityNoTezWithdrawnExpected           : Ligo.int = Ligo.int_from_literal "18"
let[@inline] error_RemoveLiquidityNoKitWithdrawnExpected           : Ligo.int = Ligo.int_from_literal "19"
let[@inline] error_RemoveLiquidityCantWithdrawEnoughTez            : Ligo.int = Ligo.int_from_literal "20"
let[@inline] error_RemoveLiquidityTooMuchTezWithdrawn              : Ligo.int = Ligo.int_from_literal "21"
let[@inline] error_RemoveLiquidityCantWithdrawEnoughKit            : Ligo.int = Ligo.int_from_literal "22"
let[@inline] error_RemoveLiquidityTooMuchKitWithdrawn              : Ligo.int = Ligo.int_from_literal "23"

let[@inline] error_LiquidationQueueTooLong                         : Ligo.int = Ligo.int_from_literal "24"
let[@inline] error_BidTooLow                                       : Ligo.int = Ligo.int_from_literal "25"
let[@inline] error_NoOpenAuction                                   : Ligo.int = Ligo.int_from_literal "26"
let[@inline] error_CannotReclaimLeadingBid                         : Ligo.int = Ligo.int_from_literal "27"
let[@inline] error_CannotReclaimWinningBid                         : Ligo.int = Ligo.int_from_literal "28"
let[@inline] error_NotAllSlicesClaimed                             : Ligo.int = Ligo.int_from_literal "29"
let[@inline] error_NotAWinningBid                                  : Ligo.int = Ligo.int_from_literal "30"
let[@inline] error_BidTicketExpired                                : Ligo.int = Ligo.int_from_literal "31"

let[@inline] error_TouchParametersInThePast                        : Ligo.int = Ligo.int_from_literal "32"

let[@inline] error_InsufficientFunds                               : Ligo.int = Ligo.int_from_literal "33"
let[@inline] error_WithdrawTezFailure                              : Ligo.int = Ligo.int_from_literal "34"
let[@inline] error_MintKitFailure                                  : Ligo.int = Ligo.int_from_literal "35"
let[@inline] error_BurrowIsAlreadyActive                           : Ligo.int = Ligo.int_from_literal "36"
let[@inline] error_DeactivatingAnOverburrowedBurrow                : Ligo.int = Ligo.int_from_literal "37"
let[@inline] error_DeactivatingAnInactiveBurrow                    : Ligo.int = Ligo.int_from_literal "38"
let[@inline] error_DeactivatingWithOutstandingKit                  : Ligo.int = Ligo.int_from_literal "39"
let[@inline] error_DeactivatingWithCollateralAtAuctions            : Ligo.int = Ligo.int_from_literal "40"

let[@inline] error_InvalidKitToken                                 : Ligo.int = Ligo.int_from_literal "41"
let[@inline] error_InvalidLiquidityToken                           : Ligo.int = Ligo.int_from_literal "42"
let[@inline] error_InvalidDelegationAuctionTicket                  : Ligo.int = Ligo.int_from_literal "43"
let[@inline] error_InvalidLiquidationAuctionTicket                 : Ligo.int = Ligo.int_from_literal "44"
let[@inline] error_InvalidPermission                               : Ligo.int = Ligo.int_from_literal "45"
let[@inline] error_MissingPermission                               : Ligo.int = Ligo.int_from_literal "46"
let[@inline] error_InsufficientPermission                          : Ligo.int = Ligo.int_from_literal "47"

let[@inline] error_NonExistentBurrow                               : Ligo.int = Ligo.int_from_literal "48"
let[@inline] error_BurrowHasCompletedLiquidation                   : Ligo.int = Ligo.int_from_literal "49"
let[@inline] error_UnwantedTezGiven                                : Ligo.int = Ligo.int_from_literal "50"
let[@inline] error_AuthenticationError                             : Ligo.int = Ligo.int_from_literal "51"
let[@inline] error_NotLiquidationCandidate                         : Ligo.int = Ligo.int_from_literal "52"
let[@inline] error_UnwarrantedCancellation                         : Ligo.int = Ligo.int_from_literal "53"

let[@inline] error_GetContractOptFailure                           : Ligo.int = Ligo.int_from_literal "54"

let[@inline] error_GetEntrypointOptFailureReceiveLiquidationSlice  : Ligo.int = Ligo.int_from_literal "55"
let[@inline] error_GetEntrypointOptFailureTransferPermission       : Ligo.int = Ligo.int_from_literal "56"
let[@inline] error_GetEntrypointOptFailureTransferAddress          : Ligo.int = Ligo.int_from_literal "57"
let[@inline] error_GetEntrypointOptFailureBurrowStoreTez           : Ligo.int = Ligo.int_from_literal "58"
let[@inline] error_GetEntrypointOptFailureTransferKit              : Ligo.int = Ligo.int_from_literal "59"
let[@inline] error_GetEntrypointOptFailureBurrowSendTezTo          : Ligo.int = Ligo.int_from_literal "60"
let[@inline] error_GetEntrypointOptFailureBurrowSetDelegate        : Ligo.int = Ligo.int_from_literal "61"
let[@inline] error_GetEntrypointOptFailureBurrowSendSliceToChecker : Ligo.int = Ligo.int_from_literal "62"
let[@inline] error_GetEntrypointOptFailureTransferDABidTicket      : Ligo.int = Ligo.int_from_literal "63"
let[@inline] error_GetEntrypointOptFailureTransferLqt              : Ligo.int = Ligo.int_from_literal "64"
let[@inline] error_GetEntrypointOptFailureTransferLABidTicket      : Ligo.int = Ligo.int_from_literal "65"

let[@inline] error_OperationOnUntouchedBurrow                      : Ligo.int = Ligo.int_from_literal "66"

let[@inline] error_UnauthorisedCaller                              : Ligo.int = Ligo.int_from_literal "67"
