name: Nightly - long-running tests

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v13
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Run tests
        run: nix-shell --command 'make test-long'
